name: CI Matrix Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  steply-tests:
    name: Tests (Java ${{ matrix.java-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        java-version: [ '17', '21', '25' ]   # 17 LTS | 21 LTS | 25 LTS (latest LTS)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Install Steply
        run: |
          curl -fsSL https://raw.githubusercontent.com/QABEES/steply/main/scripts/install_no_jre.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run tests
        run: steply --scenario tests/get_user_api.json --target-env env/sit1.properties
